# vim:ft=kitty

## name: Nightingale
## license: MIT
## author: Xein
## upstream: https://github.com/xein/nightingale.nvim/


background #202020
foreground #ffffff
selection_background #323232
selection_foreground #ffffff
url_color #7ebcfd
cursor #ffffff

# Tabs
active_tab_background #202020
active_tab_foreground #ffffff
inactive_tab_background  #202020
inactive_tab_foreground #727169

# normal
color0 #202020
color1 #e14c4c
color2 #89c471
color3 #ffd13b
color4 #5690ac
color5 #957FB8
color6 #9CABCA
color7 #bbbbbb

# bright
color8  #727169
color9  #FF5D62
color10 #aed97a
color11 #E6C384
color12 #81c0da
color13 #D27E99
color14 #A3D4D5
color15 #ffffff


# extended colors
color16 #FFA066
color17 #f5a284
  
